kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare-amd64-binaries
    image: ubuntu:20.04
    commands:
    - apt-get -y update && apt-get -y install make curl tar
    - make k8s-binaries
    when:
      event:
        - tag
        - pull_request

  - name: publish-hyperkube-linux-amd64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: rancher/hyperkube
      tag: "${DRONE_TAG}-linux-amd64"
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: prepare-arm64-binaries
    image: ubuntu:20.04
    commands:
    - apt-get -y update && apt-get -y install make curl tar
    - make ARCH=arm64 k8s-binaries
    when:
      event:
        - tag
        - pull_request

  - name: publish-hyperkube-linux-arm64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: rancher/hyperkube
      tag: "${DRONE_TAG}-linux-arm64"
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
---
kind: pipeline
name: windows-1809-pr

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: hyperkube-windows-1809-pr
    image: rancher/dapper:v0.5.6
    commands:
      - "docker build -f Dockerfile.windows --build-arg SERVERCORE_VERSION=1809 ."
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: publish-hyperkube-windows-1809
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile.windows
      repo: rancher/hyperkube
      tag: "${DRONE_TAG}-windows-1809"
      build_args:
        - SERVERCORE_VERSION=1809
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: windows-2004-pr

platform:
  os: windows
  arch: amd64
  version: 2004

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: rancher/drone-images:git-2004
  - name: hyperkube-windows-2004-pr
    image: rancher/dapper:v0.5.6
    commands:
      - "docker build -f Dockerfile.windows --build-arg SERVERCORE_VERSION=2004 ."
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: windows-2004

platform:
  os: windows
  arch: amd64
  version: 2004

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: rancher/drone-images:git-2004
  - name: publish-hyperkube-windows-2004
    image: rancher/drone-images:docker-2004
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile.windows
      repo: rancher/hyperkube
      tag: "${DRONE_TAG}-windows-2004"
      build_args:
        - SERVERCORE_VERSION=2004
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: windows-20H2-pr

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: rancher/drone-images:git-20H2
  - name: hyperkube-windows-20H2-pr
    image: rancher/dapper:v0.5.6
    commands:
      - "docker build -f Dockerfile.windows.20H2 --build-arg SERVERCORE_VERSION=20H2 ."
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: windows-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: rancher/drone-images:git-20H2
  - name: publish-hyperkube-windows-20H2
    image: rancher/drone-images:docker-20H2
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile.windows.20H2
      repo: rancher/hyperkube
      tag: "${DRONE_TAG}-windows-20H2"
      build_args:
        - SERVERCORE_VERSION=20H2
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: manifest

steps:
  - name: push-manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: manifest.tmpl
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
depends_on:
- linux-amd64
- linux-arm64
- windows-1809
- windows-2004
- windows-20H2
