kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: prepare-amd64-binaries
    image: ubuntu:20.04
    commands:
    - apt-get -y update && apt-get -y install make curl tar docker.io
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $(pwd)
    - make check-security
    - make k8s-binaries
    privileged: true
    volumes:
    - name: socket
      path: /var/run/docker.sock
    when:
      event:
        - tag
        - pull_request

  - name: publish-hyperkube-linux-amd64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: rancher/hyperkube
      tag: "${DRONE_TAG}-linux-amd64"
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
volumes:
- name: socket
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: prepare-arm64-binaries
    image: ubuntu:20.04
    commands:
    - apt-get -y update && apt-get -y install make curl tar docker.io
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $(pwd)
    - make check-security
    - make ARCH=arm64 k8s-binaries
    privileged: true
    volumes:
    - name: socket
      path: /var/run/docker.sock
    when:
      event:
        - tag
        - pull_request

  - name: publish-hyperkube-linux-arm64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: rancher/hyperkube
      tag: "${DRONE_TAG}-linux-arm64"
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag

volumes:
- name: socket
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: windows-1809-pr

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: hyperkube-windows-1809-pr
    image: rancher/dapper:v0.5.7
    commands:
      - "docker build -f Dockerfile.windows --build-arg SERVERCORE_VERSION=1809 ."
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: publish-hyperkube-windows-1809
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile.windows
      repo: rancher/hyperkube
      tag: "${DRONE_TAG}-windows-1809"
      build_args:
        - SERVERCORE_VERSION=1809
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: windows-20H2-pr

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: rancher/drone-images:git-20H2
  - name: hyperkube-windows-20H2-pr
    image: rancher/dapper:v0.5.7
    commands:
      - "docker build -f Dockerfile.windows.20H2 --build-arg SERVERCORE_VERSION=20H2 ."
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - pull_request

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

---
kind: pipeline
name: windows-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: rancher/drone-images:git-20H2
  - name: publish-hyperkube-windows-20H2
    image: rancher/drone-images:docker-20H2
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile.windows.20H2
      repo: rancher/hyperkube
      tag: "${DRONE_TAG}-windows-20H2"
      build_args:
        - SERVERCORE_VERSION=20H2
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
---
kind: pipeline
name: manifest

steps:
  - name: push-manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: manifest.tmpl
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
depends_on:
- linux-amd64
- linux-arm64
- windows-1809
- windows-20H2

---

kind: pipeline
name: fossa

steps:
- name: fossa
  image: rancher/drone-fossa:latest
  failure: ignore
  settings:
    api_key:
      from_secret: FOSSA_API_KEY
  when:
    instance:
      - drone-publish.rancher.io

