FROM gcr.io/google_containers/hyperkube-arm64:v1.12.10
RUN sed -i -e 's!\bmain\b!main contrib!g' /etc/apt/sources.list && \
    clean-install apt-transport-https gnupg1 curl zfsutils-linux \
    && apt-get purge gnupg \
    && clean-install \
    xfsprogs \
    open-iscsi
