FROM gcr.io/google_containers/hyperkube-arm64:v1.16.2
RUN sed -i -e 's!\bmain\b!main contrib!g' /etc/apt/sources.list && \
    apt-get update && apt-get upgrade -y && apt-get clean && \
    clean-install apt-transport-https gnupg1 curl zfsutils-linux \
    && apt-get purge gnupg \
    && clean-install \
    xfsprogs \
    open-iscsi
